app:
  datasource:
    dbemha:
      url: ${DBEMHA_URL_HOMOLOG}
      username: ${DBEMHA_USERNAME_HOMOLOG}
      password: ${DBEMHA_PASSWORD_HOMOLOG}

    dbacessos:
      url: ${DBACESSOS_URL_HOMOLOG}
      username: ${DBACESSOS_USERNAME_HOMOLOG}
      password: ${DBACESSOS_PASSWORD_HOMOLOG}

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.br.gov.ms.campogrande.apiemha.config.LegacyPostgreSQLDialect

  sql:
    init:
      platform: postgres

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://autenticacao-h.campogrande.ms.gov.br/auth/realms/campograndems
      resourceserver:
        jwt:
          jwk-set-uri: https://autenticacao-h.campogrande.ms.gov.br/auth/realms/campograndems/protocol/openid-connect/certs

services:
  emha-api: https://emha-h.campogrande.ms.gov.br/emha/api